/**
 * Ma loi nghiep vu (business error code) - on dinh, dung cho frontend/i18n.
 * Khac voi HTTP status: HTTP noi "loai loi", errorCode noi "chinh xac loi gi".
 */
export const ERROR_CODES = Object.freeze({
  // Chung
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  BAD_REQUEST: "BAD_REQUEST",

  // Xac thuc
  UNAUTHENTICATED: "UNAUTHENTICATED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  PROVIDER_MISMATCH: "PROVIDER_MISMATCH",
  MAGIC_LINK_INVALID: "MAGIC_LINK_INVALID",
  OAUTH_FAILED: "OAUTH_FAILED",

  // Phan quyen
  FORBIDDEN: "FORBIDDEN",
  INSUFFICIENT_PERMISSION: "INSUFFICIENT_PERMISSION",
});
